export const branchConst =  new Map([
  ["AD", "Artificial Intelligence and Data Science"],
  ["AE", "AERONAUTICAL ENGINEERING"],
  ["AG", "AGRICULTURAL ENGINEERING"],
  ["AL", "Artificial Intelligence and Machine Learning"],
  ["AM", "COMPUTER SCIENCE AND ENGINEERING (AI AND MACHINE LEARNING)"],
  ["AO", " AEROSPACE ENGINEERING"],
  ["AP", "APPAREL TECHNOLOGY (SS)"],
  ["AS", "AUTOMOBILE ENGINEERING (SS)"],
  ["AT", "ARTIFICIAL INTELLIGENCE AND DATA SCIENCE (SS)"],
  ["AU", "AUTOMOBILE ENGINEERING"],
  ["BC", "Bio Technology and Bio Chemical Engineering"],
  ["BM", "BIO MEDICAL ENGINEERING "],
  ["BS", "BIO TECHNOLOGY (SS)"],
  ["BT", "BIO TECHNOLOGY"],
  ["BY", "BIO MEDICAL ENGINEERING  (SS)"],
  ["CB", "COMPUTER SCIENCE AND BUSSINESS SYSTEM"],
  ["CC", "CHEMICAL AND ELECTRO CHEMICAL  ENGINEERING (SS)"],
  ["CD", "COMPUTER SCIENCE AND DESIGN"],
  ["CE", "CIVIL  ENGINEERING "],
  ["CF", "COMPUTER SCIENCE AND ENGINEERING (DATA SCIENCE)"],
  ["CG", "Computer Science and Engineering (Artificial Intelligence and Machine Learning) (SS)"],
  ["CH", "CHEMICAL  ENGINEERING "],
  ["CI", "Computer Science and Engineering (Internet of Things)"],
  ["CK", "Civil Engineering (Environmental Engineering)"],
  ["CL", "CHEMICAL  ENGINEERING (SS)"],
  ["CM", "COMPUTER SCIENCE AND ENGINEERING (SS)"],
  ["CN", "CIVIL  ENGINEERING (SS)"],
  ["CO", "COMPUTER AND  COMMUNICATION ENGINEERING"],
  ["CR", "CERAMIC TECHNOLOGY (SS)"],
  ["CS", "COMPUTER SCIENCE AND ENGINEERING"],
  ["CW", "Computer Science and Business System (SS)"],
  ["CY", "Cyber Security"],
  ["CZ", "CIVIL AND STRUCTUTURAL ENGINEERING"],
  ["EA", "Electronics and Communication (Advanced Communication Technology)"],
  ["EC", "ELECTRONICS AND COMMUNICATION ENGINEERING"],
  ["EE", "ELECTRICAL AND ELECTRONICS ENGINEERING"],
  ["EF", "Electrical and Computer Engineering"],
  ["EI", "ELECTRONICS AND INSTRUMENTATION ENGINEERING"],
  ["EL", "Electronics Engineering (VLSI Design and Technology) (SS)"],
  ["EM", "ELECTRONICS AND COMMUNICATION ENGINEERING (SS)"],
  ["EN", "ENVIRONMENTAL ENGINEERING"],
  ["ES", "ELECTRICAL AND ELECTRONICS (SANDWICH) (SS)"],
  ["EV", "Electronics Engineering (VLSI Design and Technology)"],
  ["EX", "Electronics and Computer Engineering"],
  ["EY", "ELECTRICAL AND ELECTRONICS ENGINEERING (SS)"],
  ["FD", "FOOD TECHNOLOGY "],
  ["FS", "FOOD TECHNOLOGY (SS)"],
  ["FT", "FASHION TECHNOLOGY"],
  ["FY", "FASHION TECHNOLOGY (SS)"],
  ["GI", "GEO INFORMATICS"],
  ["HT", "HANDLOOM AND TEXTILE TECHNOLOGY"],
  ["IB", "INDUSTRIAL BIO TECHNOLOGY"],
  ["IC", "INSTRUMENTATION AND CONTROL ENGINEERING"],
  ["IE", "INDUSTRIAL ENGINEERING"],
  ["IM", "INFORMATION TECHNOLOGY (SS)"],
  ["IN", "INDUSTRIAL ENGINEERING AND MANAGEMENT"],
  ["IS", "INDUSTRIAL BIO TECHNOLOGY (SS)"],
  ["IT", "INFORMATION TECHNOLOGY"],
  ["IX", "Electronic Instrumentation and Control Engineering"],
  ["IY", "INSTRUMENTATION AND CONTROL ENGINEERING (SS)"],
  ["LE", "LEATHER TECHNOLOGY"],
  ["MA", "MATERIAL SCIENCE AND ENGINEERING (SS)"],
  ["MB", "Mechanical Engineering (Automobile)"],
  ["MD", "MEDICAL ELECTRONICS"],
  ["MF", "MECHANICAL ENGINEERING (SS)"],
  ["MG", "MECHATRONICS (SS)"],
  ["ME", "MECHANICAL ENGINEERING"],
  ["MI", "MINING ENGINEERING"],
  ["MJ", "Mechanical and Smart Manufacturing"],
  ["MM", "MECHANICAL ENGINEERING (MANUFACTURING)"],
  ["MN", "MANUFACTURING ENGINEERING"],
  ["MO", "Mechanical and Mechatronics Engineering (Additive Manufacturing)"],
  ["MR", "MARINE ENGINEERING"],
  ["MS", "MECHANICAL ENGINEERING (SANDWICH) (SS)"],
  ["MT", "METALLURGICAL ENGINEERING"],
  ["MU", "MECHANICAL AND AUTOMATION ENGINEERING"],
  ["MY", "METALLURGICAL ENGINEERING (SS)"],
  ["MZ", "Mechatronics Engineering"],
  ["PA", "PLASTIC TECHNOLOGY"],
  ["PC", "PETRO CHEMICAL TECHNOLOGY"],
  ["PD", "PETRO CHEMICAL ENGINEERING"],
  ["PE", "PETROLEUM ENGINEERING"],
  ["PH", "PHARMACEUTICAL TECHNOLOGY"],
  ["PM", "PHARMACEUTICAL TECHNOLOGY (SS)"],
  ["PN", "PRODUCTION ENGINEERING (SS)"],
  ["PP", "PETROLEUM ENGINEERING AND TECHNOLOGY (SS)"],
  ["PR", "PRODUCTION ENGINEERING"],
  ["PS", "PRODUCTION ENGINEERING (SANDWICH) (SS)"],
  ["PT", "PRINTING & PACKING TECHNOLOGY"],
  ["RA", "ROBOTICS AND AUTOMATION (SS)"],
  ["RM", "ROBOTICS AND AUTOMATION"],
  ["RP", "RUBBER AND PLASTIC TECHNOLOGY"],
  ["SB", "Computer Science and Engineering (Internet of Things and Cyber Security including Block Chain Technology)"],
  ["SC", "Computer Science and Engineering (Cyber Security)"],
  ["SF", "Safety and Fire Engineering"],
  ["TC", "TEXTILE CHEMISTRY"],
  ["TS", "Computer Science and Technology"],
  ["TT", "TEXTILE TECHNOLOGY (SS)"],
  ["TX", "TEXTILE TECHNOLOGY"],
  ["XC", "CIVIL ENGINEERING (TAMIL MEDIUM)"],
  ["XM", "MECHANICAL ENGINEERING (TAMIL MEDIUM)"],
  ["XS", "COMPUTER SCIENCE AND ENGINEERING (TAMIL)"],
]);